require('dotenv').config();
const {MYSQL_HOST , MYSQL_USER , MYSQL_PASS, MYSQL_DATABASE , PORT , SMTP_HOST,
SMTP_PORT,
SMTP_USER,
SMTP_PASS } = process.env
module.exports={MYSQL_HOST , MYSQL_USER , MYSQL_PASS, MYSQL_DATABASE , PORT , SMTP_HOST,
SMTP_PORT,
SMTP_USER,
SMTP_PASS}